#!/bin/bash

# Redirect output to stderr.
exec 1>&2

# Check changes against clang-format.
error=false
for file in $(git diff --cached --name-only --diff-filter=ACMRT | grep -E "\.(cpp|hpp)$"); do
    if diff -u <(cat $file) <(clang-format-14 $file) > /dev/null ; then
        :
    else
        echo "Error: $file not formatted according to clang-format."
        error=true
    fi
done

if [ "$error" = true ]; then
    echo -e "Please run:\n"
    echo -e "  ./build.sh --format\n"
    echo "Don't forget to re-add the sources afterwards."
    exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached HEAD --
